# Generated by Django 5.0.6 on 2024-06-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='newevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
