# Generated by Django 5.0.6 on 2024-06-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0002_newevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clintname', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('eventname', models.CharField(max_length=100)),
                ('others', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
