# Generated by Django 5.0.6 on 2024-06-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0003_book_alter_register_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_from',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='book',
            name='date_to',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
