# Generated by Django 5.0.6 on 2024-06-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0004_book_date_from_book_date_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_to',
        ),
    ]
