# Generated by Django 5.0.6 on 2024-06-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0005_remove_book_date_from_remove_book_date_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_from',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='book',
            name='date_to',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
