# Generated by Django 5.0.6 on 2024-06-19 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0006_book_date_from_book_date_to'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='book',
            new_name='booked',
        ),
    ]
