# Generated by Django 5.0.6 on 2024-06-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0009_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='booked',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
