# Generated by Django 5.0.6 on 2024-06-19 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0010_contact_1_alter_booked_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_1',
            old_name='message',
            new_name='message_1',
        ),
    ]
