# Generated by Django 5.0.6 on 2024-06-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0011_rename_message_contact_1_message_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_1',
            old_name='message_1',
            new_name='message',
        ),
    ]
