# Generated by Django 5.0.6 on 2024-06-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0012_rename_message_1_contact_1_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='others',
        ),
    ]
