# Generated by Django 5.0.6 on 2024-06-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0014_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='newevent',
            name='advanceamount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
