# Generated by Django 5.0.6 on 2024-06-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0015_newevent_advanceamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='venue',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
