# Generated by Django 5.0.6 on 2024-06-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0016_booked_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='newevent',
            name='discription',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
