# Generated by Django 5.0.6 on 2024-06-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0017_newevent_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newevent',
            name='discription',
            field=models.CharField(max_length=500),
        ),
    ]
