# Generated by Django 5.0.6 on 2024-06-22 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0019_choices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='choices',
        ),
    ]
