# Generated by Django 5.0.6 on 2024-06-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0020_delete_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='newevent',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
