# Generated by Django 5.0.6 on 2024-06-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0021_newevent_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newevent',
            name='category',
        ),
        migrations.AddField(
            model_name='booked',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
