# Generated by Django 5.0.6 on 2024-06-22 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0022_remove_newevent_category_booked_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mp_app.register'),
            preserve_default=False,
        ),
    ]
