# Generated by Django 5.0.6 on 2024-06-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0023_booked_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booked',
            old_name='user',
            new_name='user_1',
        ),
    ]
