# Generated by Django 5.0.6 on 2024-06-22 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0024_rename_user_booked_user_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='user_1',
        ),
        migrations.CreateModel(
            name='book_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_app.booked')),
                ('user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_app.register')),
            ],
        ),
    ]
