# Generated by Django 5.0.6 on 2024-06-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0025_remove_booked_user_1_book_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
