# Generated by Django 5.0.6 on 2024-06-22 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0026_booked_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='paid', max_length=100)),
                ('book_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mp_app.booked')),
            ],
        ),
    ]
