# Generated by Django 5.0.6 on 2024-06-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0027_payment_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='status',
            field=models.CharField(default='paid', max_length=100),
        ),
    ]
