# Generated by Django 5.0.6 on 2024-06-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0028_booked_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='bookingstatus',
            field=models.CharField(default='booked', max_length=100),
        ),
    ]
