# Generated by Django 5.0.6 on 2024-06-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0030_newevent_fullamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='eventname',
            field=models.CharField(default='wedding', max_length=100),
        ),
    ]
