# Generated by Django 5.0.6 on 2024-06-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0031_alter_booked_eventname'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='amt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booked',
            name='eventname',
            field=models.CharField(max_length=100),
        ),
    ]
