# Generated by Django 5.0.6 on 2024-06-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp_app', '0032_booked_amt_alter_booked_eventname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_1',
            name='booking_1',
        ),
        migrations.RemoveField(
            model_name='book_1',
            name='user_1',
        ),
        migrations.AddField(
            model_name='book_1',
            name='amt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_1',
            name='bookingstatus',
            field=models.CharField(default='booked', max_length=100),
        ),
        migrations.AddField(
            model_name='book_1',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_1',
            name='clintname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_1',
            name='date_from',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='book_1',
            name='date_to',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AddField(
            model_name='book_1',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_1',
            name='eventname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_1',
            name='phone',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_1',
            name='status',
            field=models.CharField(default='paid', max_length=100),
        ),
        migrations.AddField(
            model_name='book_1',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book_1',
            name='venue',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
